version: "3.9"

services:
  devopsdb:
    image: jashu07/auto:javadb
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork
    volumes:
      - databasevolume:/var/lib/mysql
  application:
    image: jashu07/auto:javaapp
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

volumes:
  databasevolume:
